//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Admin
    {
        public long Admin_ID { get; set; }
        public string Admin_FullName { get; set; }
        public long Admin_Contact { get; set; }
        public string Admin_Gender { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_Role { get; set; }
        public System.DateTime Admin_Created_ON { get; set; }
        public int Admin_Created_By { get; set; }
        public Nullable<System.DateTime> Admin_Updated_ON { get; set; }
        public Nullable<int> Admin_Updated_By { get; set; }
        public bool Admin_IsActive { get; set; }
        public System.DateTime Admin_DOB { get; set; }
    }
}
