//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_User()
        {
            this.Products = new HashSet<Product>();
        }
    
        public long User_ID { get; set; }
        public string User_FullName { get; set; }
        public string User_Email { get; set; }
        public string User_Gender { get; set; }
        public long User_Contact { get; set; }
        public string User_Password { get; set; }
        public System.DateTime User_DOB { get; set; }
        public string User_Address { get; set; }
        public System.DateTime User_Created_ON { get; set; }
        public Nullable<System.DateTime> User_Updated_ON { get; set; }
        public bool User_IsActive { get; set; }
        public string User_Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
